name: ImageBuilderPipelineParent 

trigger: none

# It will trigger child pipelines sequentially. Not in parallel. Check parallel pipeline approach in other file
resources:
  pipelines:
  - pipeline: child-pipeline-01   # Name of the child pipeline resource
    source: image-builder-azure # Name of the child pipeline
    project: ImageBuilderAzure # Required only if the source pipeline is in another project
    trigger: true # enabled the pipeline trigger
  - pipeline: child-pipeline-02   
    source: image-builder-aws 
    project: ImageBuilderAWS 
    trigger: true
  - pipeline: child-pipeline-03   
    source: image-builder-gcp 
    project: ImageBuilderGCP 
    trigger: true 

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo 'pipelines executed successfully'
