trigger:
- none

name: "$(Build.DefinitionName)$(Rev:.r)"

pool:
  vmImage: "ubuntu-latest"

# Note: there are two variable GROUPS added in ADO pippeline. AZ_SUBS and HCP_PACKER_CREDS which containes ARM_SUBSCRIPTION_ID, ARM_TENANT_ID, ARM_CLIENT_ID, ARM_CLIENT_SECRET and HCP_CLIENT_ID, HCP_CLIENT_SECRET. without setting up these creds packer pipeline will not work. 
variables:
  currentYear: $[format('{0:yyyy}', pipeline.startTime)]
  currentMonth: $[format('{0:MM}', pipeline.startTime)]
  versionPrefix: $(currentYear).$(currentMonth)
  versionPatch: $[counter(format('{0:yyyyMM}', pipeline.startTime), 0)]
  imageVersion: '$(versionPrefix).$(versionPatch)'

jobs:
- job: packer
  timeoutInMinutes: 0
  steps:

  - task: Bash@3
    name: BuildAgentIP
    inputs: 
      targetType: 'inline'
      script: |
        ipaddress=$(curl -s http://ipinfo.io/ip)
        echo "##vso[task.setvariable variable=address;isOutput=true;]$ipaddress"

  - task: Bash@3
    displayName: "packer build"
    inputs:
      filePath: scripts/packer.sh
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    env: 
      PKR_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
      PKR_VAR_tenant_id: $(ARM_TENANT_ID)
      PKR_VAR_client_id: $(ARM_CLIENT_ID)
      PKR_VAR_client_secret: $(ARM_CLIENT_SECRET)
      HCP_CLIENT_ID: $(HCP_CLIENT_ID)
      HCP_CLIENT_SECRET: $(HCP_CLIENT_SECRET)
